package com.alun.common.models

enum class Lang(val s: String) {
    AFR("afr"),
    AIN("ain"),
    ALG("alg"),
    AMH("amh"),
    ARA("ara"),
    ARN("arn"),
    BNT("bnt"),
    BRE("bre"),
    BUL("bul"),
    BUR("bur"),
    CHI("chi"),
    CHN("chn"),
    CZE("cze"),
    DAN("dan"),
    DUT("dut"),
    ENG("eng"),
    EPO("epo"),
    EST("est"),
    FIL("fil"),
    FIN("fin"),
    FRE("fre"),
    GEO("geo"),
    GER("ger"),
    GLG("glg"),
    GRC("grc"),
    GRE("gre"),
    HAW("haw"),
    HEB("heb"),
    HIN("hin"),
    HUN("hun"),
    ICE("ice"),
    IND("ind"),
    ITA("ita"),
    KHM("khm"),
    KOR("kor"),
    KUR("kur"),
    LAT("lat"),
    MAL("mal"),
    MAO("mao"),
    MAY("may"),
    MNC("mnc"),
    MOL("mol"),
    MON("mon"),
    NOR("nor"),
    PER("per"),
    POL("pol"),
    POR("por"),
    RUM("rum"),
    RUS("rus"),
    SAN("san"),
    SCR("scr"),
    SLO("slo"),
    SLV("slv"),
    SOM("som"),
    SPA("spa"),
    SWA("swa"),
    SWE("swe"),
    TAH("tah"),
    TAM("tam"),
    THA("tha"),
    TIB("tib"),
    TUR("tur"),
    URD("urd"),
    VIE("vie"),
    YID("yid"),
    ;

    companion object {
        private val mapping = values().associateBy(Lang::s)
        fun fromStr(s: String) = mapping[s] ?: error("Look up failed for \"$s\" in Lang")
    }
}
